In [2]:
import numpy as np
import random

In [101]:
class MineSweeper():
    
    def __init__(self, board_length, num_mines):
        assert num_mines <= board_length**2, 'More mines than spots on the board'
        
        # If a user goes to a place, replace 0 with a space, ' '
        # Store the numbers in the board state 
        
        self.length = board_length
        self.board = np.zeros(shape=(self.length, self.length))
        self.board = np.array(self.board, dtype=object)
        self.mines_left = num_mines
        # locations we've already been to
        self.checked = {}
        
        self.game_over = False
        
        for _ in range(self.mines_left):
            while True:
                x = random.randint(0, self.length-1)
                y = random.randint(0, self.length-1)
                if self.board[x, y] == 0:
                    self.board[x, y] = -1
                    break
    
    def print_board(self):
        temp = np.array(self.board,dtype=object)
        temp[temp == 0] = '?'
        temp[temp == -1] = '?'
        return temp
    
    def input_move(self, x, y):
        if self.board(x, y) == -1:
            self.game_over = True
        else:
            self.check_for_bombs(x, y) 
    
    def check(self, x, y):
        if self.board[x, y] == -1:
            return False
        if x in self.checked:
            if y in self.checked[x]:
                return True
            self.checked[x].append(y)
            return False
        else:
            self.checked[x] = [y]
            return False
            
        
    def check_for_bombs(self, x, y):
        # Check locally for bombs, recursively
        count = 0
        if not self.check(x, y):
            if x - 1 >= 0 and y - 1 >= 0:
                if self.board[x-1, y-1] == -1:
                    count += 1       
            if x - 1 >= 0:
                if self.board[x-1, y] == -1:
                    count += 1        
            if x - 1 >= 0 and y + 1 < self.length:
                if self.board[x-1, y+1] == -1:
                    count += 1       
            if y + 1 < self.length:
                if self.board[x, y+1] == -1:
                    count += 1       
            if x + 1 < self.length and y + 1 < self.length:
                if self.board[x+1, y+1] == -1:
                    count += 1       
            if x + 1 < self.length:
                if self.board[x+1, y] == -1:
                    count += 1       
            if x + 1 < self.length and y - 1 >= 0:
                if self.board[x+1, y-1] == -1:
                    count += 1       
            if y - 1 >= 0:
                if self.board[x, y-1] == -1:
                    count += 1       
            if count == 0:
                self.board[x, y] = ''
                # No bombs here, look around for more
                self.propogate_search(x, y)
            else:
                self.board[x, y] = count
                
    def propogate_search(self, x, y):
        # This triggers when we clicked an square with no bomb near by
        # Want to search next spots
        if x - 1 >= 0 and y - 1 >= 0:
            self.check_for_bombs(x - 1, y - 1)       
        if x - 1 >= 0:
            self.check_for_bombs(x - 1, y)        
        if x - 1 >= 0 and y + 1 < self.length:
            self.check_for_bombs(x - 1, y + 1)      
        if y + 1 < self.length:
            self.check_for_bombs(x, y + 1)     
        if x + 1 < self.length and y + 1 < self.length:
            self.check_for_bombs(x + 1, y + 1)       
        if x + 1 < self.length:
            self.check_for_bombs(x + 1, y)       
        if x + 1 < self.length and y - 1 >= 0:
            self.check_for_bombs(x + 1, y - 1)      
        if y - 1 >= 0:
            self.check_for_bombs(x, y - 1)

In [102]:
game = MineSweeper(5, 2)

In [103]:
print(game.board)

[[0.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 0.0 0.0 -1]
 [0.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 0.0 -1 0.0]]


In [104]:
game.check_for_bombs(0,0)

In [105]:
print(game.board)

[['' '' '' 1 0.0]
 ['' '' '' 1 -1]
 ['' '' '' 1 0.0]
 ['' '' 1 1 0.0]
 ['' '' 1 -1 0.0]]


In [106]:
print(game.print_board())

[['' '' '' 1 '?']
 ['' '' '' 1 '?']
 ['' '' '' 1 '?']
 ['' '' 1 1 '?']
 ['' '' 1 '?' '?']]


In [33]:
0 not in game.checked

True

In [ ]:
np.zeroes()